/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IVirtualToken, IVirtualTokenInterface } from "../IVirtualToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isInWhitelist",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IVirtualToken__factory {
  static readonly abi = _abi;
  static createInterface(): IVirtualTokenInterface {
    return new utils.Interface(_abi) as IVirtualTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVirtualToken {
    return new Contract(address, _abi, signerOrProvider) as IVirtualToken;
  }
}
