const { TRACK, METADATA_URL_OVERRIDE_OPTIMISM_KOVAN, METADATA_URL_OVERRIDE_OPTIMISM } = process.env

/**
 * METADATA_URL_OVERRIDE_OPTIMISM_KOVAN: metadata url override for Optimism Kovan
 * METADATA_URL_OVERRIDE_OPTIMISM: metadata url override for Optimism Mainnet
 */

export { TRACK, METADATA_URL_OVERRIDE_OPTIMISM_KOVAN, METADATA_URL_OVERRIDE_OPTIMISM }
