// TODO: remove the prefixing "REACT_APP_SDK_" when migrating SDK to standalone repo.
const { REACT_APP_SDK_METADATA_URL_OVERRIDE_OPTIMISM_KOVAN, REACT_APP_SDK_METADATA_URL_OVERRIDE_OPTIMISM } = process.env

/**
 * METADATA_URL_OVERRIDE_OPTIMISM_KOVAN: metadata url override for Optimism Kovan
 * METADATA_URL_OVERRIDE_OPTIMISM: metadata url override for Optimism Mainnet
 */

export {
    REACT_APP_SDK_METADATA_URL_OVERRIDE_OPTIMISM_KOVAN as METADATA_URL_OVERRIDE_OPTIMISM_KOVAN,
    REACT_APP_SDK_METADATA_URL_OVERRIDE_OPTIMISM as METADATA_URL_OVERRIDE_OPTIMISM,
}
